version: '3.3'

services:
  app:
    image: php:8.1-apache
    container_name: mortystock_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
      - ./src/controllers/banco.sqlite:/var/www/html/src/controllers/banco.sqlite
    environment:
      - DB_PATH=/var/www/html/src/controllers/banco.sqlite
    depends_on:
      - db
    working_dir: /var/www/html
    labels:
      - "traefik.enable=true" # Ativa o Traefik para este serviço
      - "traefik.http.routers.mortystock.rule=Host(`mortystock.mosetech.com.br`)" # Define o subdomínio
      - "traefik.http.routers.mortystock.entrypoints=web" # Define o uso da porta HTTP
      - "traefik.http.routers.mortystock.entrypoints=websecure" # Define o uso da porta HTTPS
      - "traefik.http.routers.mortystock.tls=true" # Ativa o TLS para HTTPS
      - "traefik.http.services.mortystock.loadbalancer.server.port=80" # Porta exposta pela aplicação

  db:
    image: postgres:15
    container_name: mortystock_db
    environment:
      POSTGRES_USER: trabalho_metodologia
      POSTGRES_PASSWORD: tads2024@
      POSTGRES_DB: DB_MORTYSTOCK
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
