version: '3.3'

services:
  app:
    image: php:8.1-apache
    container_name: mortystock_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
      - ./src/controllers/banco.sqlite:/var/www/html/src/controllers/banco.sqlite
    environment:
      - DB_PATH=/var/www/html/src/controllers/banco.sqlite
    depends_on:
      - db
    working_dir: /var/www/html

  db:
    image: postgres:15
    container_name: mortystock_db
    environment:
      POSTGRES_USER: trabalho_metodologia
      POSTGRES_PASSWORD: tads2024@
      POSTGRES_DB: DB_MORTYSTOCK
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: mortystock_nginx
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

volumes:
  postgres_data: