version: '3.8'

services:
  app:
    build: .
    container_name: mortystock_app
    ports:
      - "5200:5200" # Porta mapeada para acesso direto (opcional, pode ser removida)
    volumes:
      - .:/var/www/html
    environment:
      - DB_PATH=/var/www/html/banco.sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mortystock.rule=Host(`mortystock.mosetech.com.br`)"
      - "traefik.http.routers.mortystock.entrypoints=websecure"
      - "traefik.http.routers.mortystock.tls.certresolver=myresolver"
    networks:
      - traefik_network
    restart: always

networks:
  traefik_network:
    external: true
