version: '3.3'

services:
  app:
    image: php:8.1-apache
    container_name: mortystock_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
      - ./src/controllers/banco.sqlite:/var/www/html/src/controllers/banco.sqlite
    environment:
      - DB_PATH=/var/www/html/src/controllers/banco.sqlite
    networks:
      - mortystock_network
    restart: always

  db:
    image: postgres:15
    container_name: mortystock_db
    environment:
      POSTGRES_USER: trabalho_metodologia
      POSTGRES_PASSWORD: tads2024@
      POSTGRES_DB: DB_MORTYSTOCK
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mortystock_network
    restart: always

volumes:
  postgres_data: # Declaração do volume nomeado

networks:
  mortystock_network:
    driver: bridge
